baseurl: /
paginate: 10
paginate_path: "/page:num"
permalink: "/articles/:title/"
pygments:true
hosturl: "http://jervan.me"
name: Jervan's Blog
description: A Jekyll blog template designed by Jervan
paginator_barnum: 9
author: Jervan
navbar:
    - name: 关于
      url: /about/
      title: 关于
    - name: 分类
      url: /categories/
      title: 按类别查看文章
    - name: 标签
      url: /tags/
      title: 按标签查看文章
    - name: 留言薄
      url: /guestbook/
      title: 留言板
    - name: 归档
      url: /archive/
      title: 全站归档
    - name: 书单
      url: /booklist/
      title: 好书推荐
    - name: 资源列表
      url: /resources/
      title: 啥都有~


